---
env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - import
  - jest
  - jsdoc
  - prettier
  - react
extends:
  - airbnb-base
  - plugin:@next/next/recommended
  - plugin:jest/recommended
  - plugin:jsdoc/recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
rules:
  valid-jsdoc: 'off'
  jsdoc/check-types: 'off'
  jsdoc/require-param: 'off'
  jsdoc/require-returns: 'off'
  import/extensions: [warn, {js: never}]
  import/no-extraneous-dependencies: 'off'
  import/no-named-as-default: 'off'
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/no-try-expect: 'off'
  jest/valid-expect: error
  jest/no-conditional-expect: 'off'
  react/react-in-jsx-scope: 'off'
  react/jsx-props-no-spreading: 'off'
  react/forbid-prop-types: 'off'
  prettier/prettier:
    - error
    - {
      singleQuote: true,
      semi: false,
      trailingComma: all
    }
settings:
  import/resolver:
    node:
      moduleDirectory:
        - ./src
        - ./node_modules
  jsdoc:
    mode: typescript
