## created by @opbi/ncm
---
component:
  type: page
  name: ncm-preset-page
  description: the config preset for [page] used by ncm
  keywords: standard, preset, ncm, config, template
  private: false
owner:
  type: organisation
  github: opbi
  name: OPBI
  email: engineering@opbi.org
